### ISSUE TITLE
OverflowError: Python int too large to convert to C long in pyptrace

### ISSUE THREAD

**Issue by kikimo** [kikimo/pygdb#3]
```txt
Traceback (most recent call last):
  File "./pygdb.py", line 502, in <module>
    PyGdb(tracee_binary).cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "./pygdb.py", line 260, in do_run
    bp.install(self.tracee_pid)
  File "/home/alex/src/pygdb/breakpoint.py", line 64, in install
    self._install(pid)
  File "/home/alex/src/pygdb/breakpoint.py", line 42, in _install
    pyptrace.poketext(pid, self.iaddr, self.tampered_text)
  File "build/bdist.linux-x86_64/egg/pyptrace/__init__.py", line 155, in wrapper
    
  File "build/bdist.linux-x86_64/egg/pyptrace/__init__.py", line 233, in poketext
    
OverflowError: Python int too large to convert to C long
```

**Comment by kikimo** [comment]
fixed
